project:
  name: ^{name}^
  author: ^{author}^
  version: 1.0

minecraft:
  platform: ^{platform}^ # Platform for modpack
  minecraft: ^{minecraft}^ # Minecraft version
  loader: ^{loader}^ # Loader version

  #optional: # Optional settings
  #  xmx: 4G
  #  username: TestUser
